### ISSUE TITLE
require(syntax.php) is deprecated

### ISSUE THREAD

**Issue by zounp** [hanche/dokuwiki_color_plugin#11] opened 2023-11-08 20:26 UTC
DokuwikiI gets:

2023-11-08 00:46:19		require(syntax.php) is deprecated. It was called from require() in /home/something/domains/domain.tld/public_html/wiki/lib/plugins/date/syntax.php:18 Autoloading should be used instead!

I think the plugin needs an update.

Thanks for the color syntax plugin!

**Comment by hanche** [comment] 2023-11-10 17:52
I'm confused. Isn't this a duplicate of issue #5, fixed over a year ago, 2022-09-15?

**Closed as not planned** 2023-12-09 10:35 UTC

**Comment by zounp** [comment] 2023-12-20 02:15
Looks like it.
In the mean time the error has gone away.

Thanks.

With kind regards,
Zounp
